import { useEffect, useState } from 'react';
import api from '../api/client';
import Loading from '../components/Loading';

const NotificationsPage = () => {
  const [notifications, setNotifications] = useState(null);

  const loadNotifications = async () => {
    const response = await api.get('/notifications/me');
    setNotifications(response.data.data.notifications);
  };

  useEffect(() => {
    loadNotifications();
  }, []);

  const markRead = async (id) => {
    await api.patch(`/notifications/${id}/read`);
    loadNotifications();
  };

  if (!notifications) return <Loading text="Loading notifications..." />;

  return (
    <div>
      <div className="page-header">
        <h1>Notifications</h1>
        <p className="muted">
          Alerts generated by the risk analytics module will appear here for faculty and students.
        </p>
      </div>

      <div className="card">
        {notifications.length === 0 ? (
          <p className="muted">No notifications found.</p>
        ) : (
          notifications.map((item) => (
            <div key={item._id} className={`notice ${item.read ? 'notice-read' : ''}`}>
              <div>
                <strong>{item.title}</strong>
                <p>{item.message}</p>
                <small className="muted">{new Date(item.createdAt).toLocaleString()}</small>
              </div>
              {!item.read ? (
                <button className="btn btn-secondary" onClick={() => markRead(item._id)}>
                  Mark Read
                </button>
              ) : null}
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default NotificationsPage;
